-- MySQL Script generated by MySQL Workbench


--SQLITE COMANDO
INSERT INTO usuario(id,nome_completo,email,senha) VALUES(1,'Mateus Sena','mateus_sena55@hotmail.com','12345')

INSERT INTO usuario(id,nome_completo,email,senha) VALUES(2,'Flavio Raposo','flavioraposo.90@gmail.com','12345')

CREATE TABLE IF NOT EXISTS usuario (id_usuario INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, nome_completo TEXT NOT NULL, email TEXT NOT NULL UNIQUE, senha TEXT NOT NULL)





-- -----------------------------------------------------
-- Schema xtreamingbox
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `xtreamingbox` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ;
USE `xtreamingbox` ;

-- -----------------------------------------------------
-- Table `xtreamingbox`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `xtreamingbox`.`usuario` (
  `idusuario` INT NOT NULL AUTO_INCREMENT,
  `nome_completo` VARCHAR(255) NULL,
  `email` VARCHAR(255) NULL,
  `senha` VARCHAR(8) NULL,
  PRIMARY KEY (`idusuario`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;

-- -----------------------------------------------------
-- Table `xtreamingbox`.`plataforma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `xtreamingbox`.`plataforma` (
  `idplataforma` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `imagemplataforma` VARCHAR(45) NULL,
  PRIMARY KEY (`idplataforma`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `xtreamingbox`.`series`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `xtreamingbox`.`series` (
  `idseries` INT NOT NULL AUTO_INCREMENT,
  `plataforma_idplataforma` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `ano` INT NULL,
  `genero` VARCHAR(45) NULL,
  `avalicacao` INT NULL,
  `temporada` INT NULL,
  PRIMARY KEY (`idseries`, `plataforma_idplataforma`),
  INDEX `fk_series_plataforma_idx` (`plataforma_idplataforma` ASC) VISIBLE,
  CONSTRAINT `fk_series_plataforma`
    FOREIGN KEY (`plataforma_idplataforma`)
    REFERENCES `xtreamingbox`.`plataforma` (`idplataforma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin
PACK_KEYS = 0
ROW_FORMAT = COMPRESSED;


-- -----------------------------------------------------
-- Table `xtreamingbox`.`situacao_serie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `xtreamingbox`.`situacao_serie` (
  `idsituacao_serie` INT NOT NULL AUTO_INCREMENT,
  `desejo_assistir` VARCHAR(45) NULL,
  `visto` VARCHAR(45) NULL,
  `series_idseries` INT NOT NULL,
  `series_plataforma_idplataforma` INT NOT NULL,
  `usuario_idtable1` INT NOT NULL,
  PRIMARY KEY (`idsituacao_serie`),
  INDEX `fk_situacao_serie_series1_idx` (`series_idseries` ASC, `series_plataforma_idplataforma` ASC) VISIBLE,
  INDEX `fk_situacao_serie_usuario1_idx` (`usuario_idtable1` ASC) VISIBLE,
  CONSTRAINT `fk_situacao_serie_series1`
    FOREIGN KEY (`series_idseries` , `series_plataforma_idplataforma`)
    REFERENCES `xtreamingbox`.`series` (`idseries` , `plataforma_idplataforma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_situacao_serie_usuario1`
    FOREIGN KEY (`usuario_idtable1`)
    REFERENCES `xtreamingbox`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
